#include "fsnetextension_closeairsupport.h"
#include "fssimulation.h"

FsNetExtension_CloseAirSupport::FsNetExtension_CloseAirSupport() : initRemainTime(15.0*60.0), maxNumTank(10)
{
	remainTime=0.0;
}

/* virtual */ const char *FsNetExtension_CloseAirSupport::GetExtensionName(void) const
{
	return "CLOSEAIRSUPPORT";
}

/* virtual */ YSBOOL FsNetExtension_CloseAirSupport::IsExclusive(void) const
{
	return YSTRUE;
}

/* virtual */ YSBOOL FsNetExtension_CloseAirSupport::IsRunning(void)
{
	if(remainTime>YsTolerance)
	{
		return YSTRUE;
	}
	return YSFALSE;
}

/* virtual */ void FsNetExtension_CloseAirSupport::StartSimulation(FsSocketServer &server) {}

/* virtual */ void FsNetExtension_CloseAirSupport::OnNetConsoleCommand(FsSocketServer &server,enum FSNET_CONSOLE_COMMAND command)
{
	switch(command)
	{
	case FSNCC_SVR_STARTCLOSEAIRSUPPORTMISSION:
		if(remainTime<YsTolerance && server.extensionCollection->HasRunningExclusive()==YSFALSE)
		{
			remainTime=initRemainTime;

			fsConsole.Printf("**** CLOSE AIR SUPPORT MISSION START ****");
			server.BroadcastTextMessage("**** CLOSE AIR SUPPORT MISSION START ****");
		}
		break;
	case FSNCC_SVR_TERMINATEMISSION:
		if(remainTime>YsTolerance)
		{
			remainTime=0.0;

			fsConsole.Printf("CLOSE AIR SUPPORT MISSION is terminated.");
			server.BroadcastTextMessage("CLOSE AIR SUPPORT MISSION is terminated.");

			server.sim->DestroyAutoGeneratedAirAndGnd();
		}
		break;
	}
}

/* virtual */ void FsNetExtension_CloseAirSupport::OnSlashCommand(FsSocketServer &server,int clientId,const YsConstArrayMask <YsString> &argv) {}

/* virtual */ void FsNetExtension_CloseAirSupport::OnInterval(FsSocketServer &server,double passedTime)
{
	double timeElapse;
	int nTank;

	timeElapse=initRemainTime-remainTime;

	nTank=int(timeElapse/60.0)+3;
	nTank=YsBound(nTank,3,maxNumTank);
	server.sim->GenerateTank(nTank,info,YSTRUE,YSTRUE,YSTRUE,FS_IFF3,6,4);

	remainTime-=passedTime;
	if(remainTime<=YsTolerance)
	{
		server.AddMessage("**** END CLOSE AIR SUPPORT MISSION ****");
		server.sim->AddTimedMessage("**** END CLOSE AIR SUPPORT MISSION ****");
		server.BroadcastTextMessage("**** END CLOSE AIR SUPPORT MISSION ****");
	}
}
