#include "fsnetextension_intercept.h"
#include "fssimulation.h"

FsNetExtension_InterceptMission::FsNetExtension_InterceptMission() : initRemainTime(15.0*60.0)
{
	remainTime=0.0;
}

/* virtual */ const char *FsNetExtension_InterceptMission::GetExtensionName(void) const
{
	return "INTERCEPT";
}

/* virtual */ YSBOOL FsNetExtension_InterceptMission::IsExclusive(void) const
{
	return YSTRUE;
}

/* virtual */ YSBOOL FsNetExtension_InterceptMission::IsRunning(void)
{
	if(remainTime>YsTolerance)
	{
		return YSTRUE;
	}
	return YSFALSE;
}

/* virtual */ void FsNetExtension_InterceptMission::StartSimulation(FsSocketServer &server)
{
	info=*server.imInfo;
}

/* virtual */ void FsNetExtension_InterceptMission::OnNetConsoleCommand(FsSocketServer &server,enum FSNET_CONSOLE_COMMAND command)
{
	switch(command)
	{
	case FSNCC_SVR_STARTINTERCEPTMISSION:
		if(remainTime<YsTolerance && server.extensionCollection->HasRunningExclusive()==YSFALSE)
		{
			remainTime=initRemainTime;

			fsConsole.Printf("**** INTERCEPT MISSION START ****");
			server.BroadcastTextMessage("**** INTERCEPT MISSION START ****");
		}
		break;
	case FSNCC_SVR_TERMINATEMISSION:
		if(remainTime>YsTolerance)
		{
			remainTime=0.0;

			fsConsole.Printf("INTERCEPT MISSION is terminated.");
			server.BroadcastTextMessage("INTERCEPT MISSION is terminated.");

			server.sim->DestroyAutoGeneratedAirAndGnd();
		}
		break;
	}
}

/* virtual */ void FsNetExtension_InterceptMission::OnSlashCommand(FsSocketServer &server,int clientId,const YsConstArrayMask <YsString> &argv) {}

/* virtual */ void FsNetExtension_InterceptMission::OnInterval(FsSocketServer &server,double passedTime)
{
	double timeElapse;
	int nAttacker;

	timeElapse=initRemainTime-remainTime;

	nAttacker=int(timeElapse/120.0)+1;
	nAttacker=YsBound(nAttacker,1,info.attackerInfo.maxNumAttacker);
	server.sim->GenerateAttackerAirplane(nAttacker,info.attackerInfo,20000.0,8000.0,YSFALSE,300.0);

	remainTime-=passedTime;
	if(remainTime<=YsTolerance)
	{
		server.AddMessage("**** END INTERCEPT MISSION ****");
		server.sim->AddTimedMessage("**** END INTERCEPT MISSION ****");
		server.BroadcastTextMessage("**** END INTERCEPT MISSION ****");
	}
}
