#include "fsnetextension_endurance.h"
#include "fsnetconfig.h"
#include "fssimulation.h"

FsNetExtension_EnduranceMode::FsNetExtension_EnduranceMode() : initRemainTime(15.0*60.0), initGLimit(4.0)
{
	remainTime=0.0;
	gLimit=initGLimit;
	nEnemyMax=0;
	allowAAM=YSTRUE;
	jet=YSTRUE;
	ww2=YSTRUE;
}

/* virtual */ const char *FsNetExtension_EnduranceMode::GetExtensionName(void) const
{
	return "ENDURANCE";
}

/* virtual */ YSBOOL FsNetExtension_EnduranceMode::IsExclusive(void) const
{
	return YSTRUE;
}

/* virtual */ YSBOOL FsNetExtension_EnduranceMode::IsRunning(void)
{
	if(remainTime>YsTolerance)
	{
		return YSTRUE;
	}
	return YSFALSE;
}

/* virtual */ void FsNetExtension_EnduranceMode::StartSimulation(FsSocketServer &server)
{
	allowAAM=server.netcfg->useMissile;
}

/* virtual */ void FsNetExtension_EnduranceMode::OnNetConsoleCommand(FsSocketServer &server,enum FSNET_CONSOLE_COMMAND command)
{
	switch(command)
	{
	case FSNCC_SVR_STARTENDURANCEMODE_JET:
		if(remainTime<YsTolerance && server.extensionCollection->HasRunningExclusive()==YSFALSE)
		{
			remainTime=initRemainTime;
			gLimit=initGLimit;
			nEnemyMax=0;
			jet=YSTRUE;
			ww2=YSFALSE;

			fsConsole.Printf("**** ENDURANCE MODE START (Jet) ****");
			server.BroadcastTextMessage("**** ENDURANCE MODE START (Jet) ****");
		}
		break;
	case FSNCC_SVR_STARTENDURANCEMODE_WW2:
		if(remainTime<YsTolerance && server.extensionCollection->HasRunningExclusive()==YSFALSE)
		{
			remainTime=initRemainTime;
			gLimit=initGLimit;
			nEnemyMax=0;
			jet=YSFALSE;
			ww2=YSTRUE;

			fsConsole.Printf("**** ENDURANCE MODE START (Ww2) ****");
			server.BroadcastTextMessage("**** ENDURANCE MODE START (Ww2) ****");
		}
		break;
	case FSNCC_SVR_TERMINATEMISSION:
		if(remainTime>YsTolerance)
		{
			remainTime=0.0;

			fsConsole.Printf("ENDURANCE MODE is terminated.");
			server.BroadcastTextMessage("ENDURANCE MODE is terminated.");

			server.sim->DestroyAutoGeneratedAirAndGnd();
		}
		break;
	}
}

/* virtual */ void FsNetExtension_EnduranceMode::OnSlashCommand(FsSocketServer &server,int clientId,const YsConstArrayMask <YsString> &argv) {}

/* virtual */ void FsNetExtension_EnduranceMode::OnInterval(FsSocketServer &server,double passedTime)
{
	server.sim->GenerateEnemyAirplane(nEnemyMax,gLimit,remainTime,allowAAM,jet,ww2);

	remainTime-=passedTime;
	if(remainTime<=YsTolerance)
	{
		server.AddMessage("**** END ENDURANCE MODE ****");
		server.sim->AddTimedMessage("**** END ENDURANCE MODE ****");
		server.BroadcastTextMessage("**** END ENDURANCE MODE ****");
	}
}
